/*
 * generated by Xtext 2.24.0
 */
package edu.dtu.s144874.thesis.ppid.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PpidUiModule extends AbstractPpidUiModule {

	public PpidUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
