/*
 * generated by Xtext 2.24.0
 */
package edu.dtu.s144874.thesis.ppid.ui.tests;

import com.google.inject.Injector;
import edu.dtu.s144874.thesis.ppid.ui.internal.PpidActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class PpidUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PpidActivator.getInstance().getInjector("edu.dtu.s144874.thesis.ppid.Ppid");
	}

}
