/*
 * generated by Xtext 2.24.0
 */
package edu.dtu.s144874.thesis.ppid.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPpidScopeProvider extends DelegatingScopeProvider {
}
