/*
 * generated by Xtext 2.24.0
 */
package edu.dtu.s144874.thesis.ppid.ui;

import com.google.inject.Injector;
import edu.dtu.s144874.thesis.ppid.ui.internal.PpidActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PpidExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(PpidActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		PpidActivator activator = PpidActivator.getInstance();
		return activator != null ? activator.getInjector(PpidActivator.EDU_DTU_S144874_THESIS_PPID_PPID) : null;
	}

}
