/*
 * generated by Xtext 2.24.0
 */
package edu.dtu.s144874.thesis.ppid.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class PpidWebModule extends AbstractPpidWebModule {
}
