/**
 * generated by Xtext 2.24.0
 */
package edu.dtu.s144874.thesis.ppid.ppid;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.dtu.s144874.thesis.ppid.ppid.Model#getEntites <em>Entites</em>}</li>
 *   <li>{@link edu.dtu.s144874.thesis.ppid.ppid.Model#getSources <em>Sources</em>}</li>
 *   <li>{@link edu.dtu.s144874.thesis.ppid.ppid.Model#getSinks <em>Sinks</em>}</li>
 *   <li>{@link edu.dtu.s144874.thesis.ppid.ppid.Model#getRules <em>Rules</em>}</li>
 *   <li>{@link edu.dtu.s144874.thesis.ppid.ppid.Model#getStart <em>Start</em>}</li>
 *   <li>{@link edu.dtu.s144874.thesis.ppid.ppid.Model#getEnd <em>End</em>}</li>
 *   <li>{@link edu.dtu.s144874.thesis.ppid.ppid.Model#getProcesses <em>Processes</em>}</li>
 * </ul>
 *
 * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Entites</b></em>' containment reference list.
   * The list contents are of type {@link edu.dtu.s144874.thesis.ppid.ppid.Entity}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entites</em>' containment reference list.
   * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getModel_Entites()
   * @model containment="true"
   * @generated
   */
  EList<Entity> getEntites();

  /**
   * Returns the value of the '<em><b>Sources</b></em>' containment reference list.
   * The list contents are of type {@link edu.dtu.s144874.thesis.ppid.ppid.Source}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sources</em>' containment reference list.
   * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getModel_Sources()
   * @model containment="true"
   * @generated
   */
  EList<Source> getSources();

  /**
   * Returns the value of the '<em><b>Sinks</b></em>' containment reference list.
   * The list contents are of type {@link edu.dtu.s144874.thesis.ppid.ppid.Sink}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sinks</em>' containment reference list.
   * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getModel_Sinks()
   * @model containment="true"
   * @generated
   */
  EList<Sink> getSinks();

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link edu.dtu.s144874.thesis.ppid.ppid.ExtendedRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getModel_Rules()
   * @model containment="true"
   * @generated
   */
  EList<ExtendedRule> getRules();

  /**
   * Returns the value of the '<em><b>Start</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' containment reference.
   * @see #setStart(StartRule)
   * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getModel_Start()
   * @model containment="true"
   * @generated
   */
  StartRule getStart();

  /**
   * Sets the value of the '{@link edu.dtu.s144874.thesis.ppid.ppid.Model#getStart <em>Start</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' containment reference.
   * @see #getStart()
   * @generated
   */
  void setStart(StartRule value);

  /**
   * Returns the value of the '<em><b>End</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End</em>' containment reference.
   * @see #setEnd(EndRule)
   * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getModel_End()
   * @model containment="true"
   * @generated
   */
  EndRule getEnd();

  /**
   * Sets the value of the '{@link edu.dtu.s144874.thesis.ppid.ppid.Model#getEnd <em>End</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End</em>' containment reference.
   * @see #getEnd()
   * @generated
   */
  void setEnd(EndRule value);

  /**
   * Returns the value of the '<em><b>Processes</b></em>' containment reference list.
   * The list contents are of type {@link edu.dtu.s144874.thesis.ppid.ppid.Process}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Processes</em>' containment reference list.
   * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getModel_Processes()
   * @model containment="true"
   * @generated
   */
  EList<edu.dtu.s144874.thesis.ppid.ppid.Process> getProcesses();

} // Model
