/**
 * generated by Xtext 2.24.0
 */
package edu.dtu.s144874.thesis.ppid.ppid;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Output Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.dtu.s144874.thesis.ppid.ppid.OutputValue#getValueInt <em>Value Int</em>}</li>
 *   <li>{@link edu.dtu.s144874.thesis.ppid.ppid.OutputValue#getValueString <em>Value String</em>}</li>
 *   <li>{@link edu.dtu.s144874.thesis.ppid.ppid.OutputValue#getValueRef <em>Value Ref</em>}</li>
 * </ul>
 *
 * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getOutputValue()
 * @model
 * @generated
 */
public interface OutputValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Value Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Int</em>' attribute.
   * @see #setValueInt(int)
   * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getOutputValue_ValueInt()
   * @model
   * @generated
   */
  int getValueInt();

  /**
   * Sets the value of the '{@link edu.dtu.s144874.thesis.ppid.ppid.OutputValue#getValueInt <em>Value Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Int</em>' attribute.
   * @see #getValueInt()
   * @generated
   */
  void setValueInt(int value);

  /**
   * Returns the value of the '<em><b>Value String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value String</em>' attribute.
   * @see #setValueString(String)
   * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getOutputValue_ValueString()
   * @model
   * @generated
   */
  String getValueString();

  /**
   * Sets the value of the '{@link edu.dtu.s144874.thesis.ppid.ppid.OutputValue#getValueString <em>Value String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value String</em>' attribute.
   * @see #getValueString()
   * @generated
   */
  void setValueString(String value);

  /**
   * Returns the value of the '<em><b>Value Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Ref</em>' containment reference.
   * @see #setValueRef(PropertyReference)
   * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getOutputValue_ValueRef()
   * @model containment="true"
   * @generated
   */
  PropertyReference getValueRef();

  /**
   * Sets the value of the '{@link edu.dtu.s144874.thesis.ppid.ppid.OutputValue#getValueRef <em>Value Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Ref</em>' containment reference.
   * @see #getValueRef()
   * @generated
   */
  void setValueRef(PropertyReference value);

} // OutputValue
