/**
 * generated by Xtext 2.24.0
 */
package edu.dtu.s144874.thesis.ppid.ppid;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.dtu.s144874.thesis.ppid.ppid.SimpleDataType#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getSimpleDataType()
 * @model
 * @generated
 */
public interface SimpleDataType extends Type
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link edu.dtu.s144874.thesis.ppid.ppid.PrimitiveType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see edu.dtu.s144874.thesis.ppid.ppid.PrimitiveType
   * @see #setType(PrimitiveType)
   * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getSimpleDataType_Type()
   * @model
   * @generated
   */
  PrimitiveType getType();

  /**
   * Sets the value of the '{@link edu.dtu.s144874.thesis.ppid.ppid.SimpleDataType#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see edu.dtu.s144874.thesis.ppid.ppid.PrimitiveType
   * @see #getType()
   * @generated
   */
  void setType(PrimitiveType value);

} // SimpleDataType
