/**
 * generated by Xtext 2.24.0
 */
package edu.dtu.s144874.thesis.ppid.ppid;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Source Update</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.dtu.s144874.thesis.ppid.ppid.SourceUpdate#getSource <em>Source</em>}</li>
 *   <li>{@link edu.dtu.s144874.thesis.ppid.ppid.SourceUpdate#getProperty <em>Property</em>}</li>
 *   <li>{@link edu.dtu.s144874.thesis.ppid.ppid.SourceUpdate#getUpdate <em>Update</em>}</li>
 * </ul>
 *
 * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getSourceUpdate()
 * @model
 * @generated
 */
public interface SourceUpdate extends EObject
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference.
   * @see #setSource(Source)
   * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getSourceUpdate_Source()
   * @model
   * @generated
   */
  Source getSource();

  /**
   * Sets the value of the '{@link edu.dtu.s144874.thesis.ppid.ppid.SourceUpdate#getSource <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' reference.
   * @see #getSource()
   * @generated
   */
  void setSource(Source value);

  /**
   * Returns the value of the '<em><b>Property</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property</em>' reference.
   * @see #setProperty(Property)
   * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getSourceUpdate_Property()
   * @model
   * @generated
   */
  Property getProperty();

  /**
   * Sets the value of the '{@link edu.dtu.s144874.thesis.ppid.ppid.SourceUpdate#getProperty <em>Property</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property</em>' reference.
   * @see #getProperty()
   * @generated
   */
  void setProperty(Property value);

  /**
   * Returns the value of the '<em><b>Update</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Update</em>' containment reference.
   * @see #setUpdate(Update)
   * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getSourceUpdate_Update()
   * @model containment="true"
   * @generated
   */
  Update getUpdate();

  /**
   * Sets the value of the '{@link edu.dtu.s144874.thesis.ppid.ppid.SourceUpdate#getUpdate <em>Update</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Update</em>' containment reference.
   * @see #getUpdate()
   * @generated
   */
  void setUpdate(Update value);

} // SourceUpdate
