/**
 * generated by Xtext 2.24.0
 */
package edu.dtu.s144874.thesis.ppid.ppid;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getType()
 * @model
 * @generated
 */
public interface Type extends EObject
{
} // Type
