/**
 * generated by Xtext 2.24.0
 */
package edu.dtu.s144874.thesis.ppid.ppid;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Update Below</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getUpdateBelow()
 * @model
 * @generated
 */
public interface UpdateBelow extends Update
{
} // UpdateBelow
