/**
 * generated by Xtext 2.24.0
 */
package edu.dtu.s144874.thesis.ppid.ppid;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Update Change</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.dtu.s144874.thesis.ppid.ppid.UpdateChange#getM <em>M</em>}</li>
 * </ul>
 *
 * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getUpdateChange()
 * @model
 * @generated
 */
public interface UpdateChange extends Update
{
  /**
   * Returns the value of the '<em><b>M</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>M</em>' attribute.
   * @see #setM(int)
   * @see edu.dtu.s144874.thesis.ppid.ppid.PpidPackage#getUpdateChange_M()
   * @model
   * @generated
   */
  int getM();

  /**
   * Sets the value of the '{@link edu.dtu.s144874.thesis.ppid.ppid.UpdateChange#getM <em>M</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>M</em>' attribute.
   * @see #getM()
   * @generated
   */
  void setM(int value);

} // UpdateChange
