/*
 * generated by Xtext 2.24.0
 */
package edu.dtu.s144874.thesis.ppid.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractPpidValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(edu.dtu.s144874.thesis.ppid.ppid.PpidPackage.eINSTANCE);
		return result;
	}
}
