/*
 * generated by Xtext 2.24.0
 */
package edu.dtu.s144874.thesis.ppid.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PpidAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("edu/dtu/s144874/thesis/ppid/parser/antlr/internal/InternalPpid.tokens");
	}
}
