/*
 * generated by Xtext 2.24.0
 */
package edu.dtu.s144874.thesis.ppid.parser.antlr;

import com.google.inject.Inject;
import edu.dtu.s144874.thesis.ppid.parser.antlr.internal.InternalPpidParser;
import edu.dtu.s144874.thesis.ppid.services.PpidGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class PpidParser extends AbstractAntlrParser {

	@Inject
	private PpidGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPpidParser createParser(XtextTokenStream stream) {
		return new InternalPpidParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public PpidGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PpidGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
