/*
 * generated by Xtext 2.24.0
 */
package edu.dtu.s144874.thesis.ppid.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link PpidWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractPpidWebModule extends DefaultWebModule {

}
