/*
 * generated by Xtext 2.24.0
 */
package edu.dtu.s144874.thesis.ppid;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PpidRuntimeModule extends AbstractPpidRuntimeModule {
}
