/*
 * generated by Xtext 2.24.0
 */
package edu.dtu.s144874.thesis.ppid;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PpidStandaloneSetup extends PpidStandaloneSetupGenerated {

	public static void doSetup() {
		new PpidStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
